# jira2pr — assembler convenience targets.
# VALID_PLATFORMS must be kept in sync with scripts/assembler/platforms/__init__.py PLATFORMS keys.

.DEFAULT_GOAL := help
VALID_PLATFORMS := copilot claude opencode
TARGET_DIR ?= examples-autogenerated/$(PLATFORM)

.PHONY: install help

install: ## Assemble platform files. Usage: make install PLATFORM=<copilot|claude|opencode> [TARGET_DIR=<dir>]
	@if [ -z "$(PLATFORM)" ]; then \
		echo "ERROR: PLATFORM is required. Valid platforms: $(VALID_PLATFORMS)"; \
		exit 1; \
	fi
	@case " $(VALID_PLATFORMS) " in \
		*" $(PLATFORM) "*) ;; \
		*) echo "ERROR: unknown PLATFORM '$(PLATFORM)'. Valid platforms: $(VALID_PLATFORMS)"; exit 1 ;; \
	esac
	python3 scripts/assemble.py --target-dir $(TARGET_DIR) --platform $(PLATFORM)

help: ## Show this help message
	@echo "jira2pr Makefile targets:"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  make %-10s %s\n", $$1, $$2}'
	@echo ""
	@echo "Variables:"
	@echo "  PLATFORM    Required for install. One of: $(VALID_PLATFORMS)"
	@echo "  TARGET_DIR  Optional. Default: examples-autogenerated/<platform>"
