"""ClaudeAssembler — generates Claude Code agent setup from canonical definitions.

This is a minimal stub.  Claude Code support is planned but not yet
feature-complete.  Currently it generates:
  - .claude/commands/<slug>.md   for each agent

Not yet implemented (see KAN-12 follow-up):
  - state/   (→ SCHEMA.md, workflow-state.tpl.md)  — add _assemble_state()
  - artifacts/  (→ SCHEMA.md)                       — add _assemble_artifacts()
"""

from __future__ import annotations

import textwrap

from assembler.base import PlatformAssembler
from assembler.registry import CanonicalRegistry
from assembler.writer import FileWriter


class ClaudeAssembler(PlatformAssembler):
    name = "claude"

    TEMPLATE_VARS: dict[str, str] = {
        "PROJECT_INSTRUCTIONS_FILE": "CLAUDE.md",
        "TASK_TRACKING_INSTRUCTION": "plan and list the tasks clearly before starting",
        "TASK_COMPLETION_INSTRUCTION": "Note each task as done after completing it",
    }

    def assemble(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        self._assemble_agents(registry, writer)

    # ------------------------------------------------------------------
    # Agents → .claude/commands/<slug>.md
    # ------------------------------------------------------------------

    def _assemble_agents(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for agent in registry.agents:
            slug = agent["slug"]
            body = registry.agent_body(slug)

            lines: list[str] = []
            lines.append(f"<!-- agent: {slug} -->")
            lines.append(f"<!-- name: {agent['name']} -->")
            lines.append(f"<!-- tier: {agent['tier']} -->")
            lines.append(f"<!-- generated by scripts/assemble.py from canonical/agents/{slug}.md -->")
            lines.append("")

            preamble = textwrap.dedent(f"""\
                > **Agent**: {agent['name']}
                > **Argument**: {agent['argument_hint']}

                Read the project instructions from `CLAUDE.md` before proceeding.

            """)

            content = "\n".join(lines) + preamble + body
            rel = f".claude/commands/{slug}.md"
            writer.put(rel, content)
