"""CopilotAssembler — generates VS Code Copilot agent setup from canonical definitions."""

from __future__ import annotations

import json
from pathlib import Path

from assembler.base import PlatformAssembler
from assembler.registry import CanonicalRegistry
from assembler.templates import generate_agents_section
from assembler.writer import FileWriter

# Capability → VS Code Copilot tool mapping
COPILOT_TOOL_MAP: dict[str, str] = {
    "read": "read",
    "edit": "edit",
    "search": "search",
    "execute": "execute",
    "delegate": "agent",
    "plan": "todo",
    "fetch": "fetch",
}


class CopilotAssembler(PlatformAssembler):
    name = "copilot"

    TEMPLATE_VARS: dict[str, str] = {
        "PROJECT_INSTRUCTIONS_FILE": "copilot-instructions.md",
        "TASK_TRACKING_INSTRUCTION": "use the `todo` tool to plan the tasks",
        "TASK_COMPLETION_INSTRUCTION": "Mark each task as completed in the todo list immediately after finishing it",
    }

    # The output root is .github/ under the target dir.
    GITHUB_PREFIX = ".github"

    def assemble(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        self._assemble_agents(registry, writer)
        self._assemble_skills(registry, writer)
        self._assemble_workflows(registry, writer)
        self._assemble_instructions(registry, writer)
        self._assemble_prompts(registry, writer)
        self._assemble_project_instructions(registry, writer)
        self._assemble_model_tiers(registry, writer)
        self._assemble_state(registry, writer)
        self._assemble_artifacts(registry, writer)
        self._copy_platform_extras(registry, writer)
        self._copy_env_example(registry, writer)

    # ------------------------------------------------------------------
    # Agents
    # ------------------------------------------------------------------

    def _assemble_agents(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for agent in registry.agents:
            slug = agent["slug"]
            tier = agent["tier"]
            model = registry.model_for_tier(tier, self.name)
            body = registry.agent_body(slug)

            tools = [COPILOT_TOOL_MAP.get(c, c) for c in agent.get("capabilities", [])]
            subagents = agent.get("subagents", [])

            lines: list[str] = ["---"]
            lines.append(f'description: "{agent["description"]}"')
            lines.append(f'name: "{agent["name"]}"')
            if agent.get("role"):
                lines.append(f'role: "{agent["role"]}"')
            lines.append(f"tools: [{', '.join(tools)}]")
            lines.append(f'model: "{model}"')
            if subagents:
                lines.append(f"agents: [{', '.join(subagents)}]")
            lines.append(f'argument-hint: "{agent["argument_hint"]}"')
            lines.append(f"user-invocable: {'true' if agent.get('user_invocable') else 'false'}")
            lines.append("---")
            lines.append("")
            lines.append(f"<!-- tier: {tier} -->")
            lines.append("")
            lines.append(f"<!-- DO NOT EDIT — generated by scripts/assemble.py from canonical/agents/{slug}.md -->")
            lines.append("")

            content = "\n".join(lines) + body
            rel = f"{self.GITHUB_PREFIX}/agents/{slug}.agent.md"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Skills
    # ------------------------------------------------------------------

    def _assemble_skills(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for skill in registry.skills:
            slug = skill["slug"]
            body = registry.skill_body(slug)

            lines: list[str] = ["---"]
            lines.append(f"name: {slug}")
            lines.append(f"description: '{skill['description']}'")
            lines.append(f"argument-hint: '{skill['argument_hint']}'")
            lines.append("---")
            lines.append("")

            content = "\n".join(lines) + body
            rel = f"{self.GITHUB_PREFIX}/skills/{slug}/SKILL.md"
            writer.put(rel, content)

            # Copy scripts/ if present
            scripts_dir = registry.skill_scripts_dir(slug)
            if scripts_dir is not None:
                writer.copy_tree(
                    scripts_dir,
                    f"{self.GITHUB_PREFIX}/skills/{slug}/scripts",
                )

    # ------------------------------------------------------------------
    # Workflows
    # ------------------------------------------------------------------

    def _assemble_workflows(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for wf_path in registry.workflow_files():
            raw = wf_path.read_text()
            content = self.substitute(raw)
            rel = f"{self.GITHUB_PREFIX}/agent-workflows/{wf_path.name}"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Instructions
    # ------------------------------------------------------------------

    def _assemble_instructions(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for instr in registry.instructions:
            slug = instr["slug"]
            body = registry.instruction_body(slug)

            lines: list[str] = ["---"]
            lines.append(f'description: "{instr["description"]}"')
            lines.append("---")
            lines.append("")

            content = "\n".join(lines) + body
            rel = f"{self.GITHUB_PREFIX}/instructions/{slug}.instructions.md"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Prompts
    # ------------------------------------------------------------------

    def _assemble_prompts(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for prompt in registry.prompts:
            slug = prompt["slug"]
            body = registry.prompt_body(slug)

            lines: list[str] = ["---"]
            lines.append(f'description: "{prompt["description"]}"')
            lines.append(f'agent: "{prompt["agent"]}"')
            lines.append(f'argument-hint: "{prompt["argument_hint"]}"')
            lines.append("---")
            lines.append("")

            content = "\n".join(lines) + body
            rel = f"{self.GITHUB_PREFIX}/prompts/{slug}.prompt.md"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Project instructions (copilot-instructions.md)
    # ------------------------------------------------------------------

    def _assemble_project_instructions(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        tpl = registry.project_instructions_tpl
        marker = "<!-- AGENTS_SECTION:AUTO_GENERATED -->"

        if marker in tpl:
            agents_section = generate_agents_section(
                registry, self.name, "copilot-instructions.md"
            )
            content = tpl.replace(marker, marker + "\n" + agents_section)
        else:
            content = tpl

        rel = f"{self.GITHUB_PREFIX}/copilot-instructions.md"
        writer.put(rel, content)

    # ------------------------------------------------------------------
    # Model tiers (model-tiers.json)
    # ------------------------------------------------------------------

    def _assemble_model_tiers(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        tiers = registry.model_tiers.get("tiers", {})
        out: dict[str, dict] = {}
        for tier_num, tier_data in sorted(tiers.items(), key=lambda x: int(x[0])):
            model = tier_data.get("models", {}).get(self.name, "")
            out[str(tier_num)] = {
                "model": model,
                "description": tier_data.get("description", ""),
            }
        content = json.dumps({"tiers": out}, indent="\t", ensure_ascii=False) + "\n"
        rel = f"{self.GITHUB_PREFIX}/model-tiers.json"
        writer.put(rel, content)

    # ------------------------------------------------------------------
    # Platform extras (scripts like apply_model_tiers.py)
    # ------------------------------------------------------------------

    def _copy_platform_extras(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        extras = registry.platform_extras_dir(self.name)
        if extras is not None:
            writer.copy_tree(extras, f"{self.GITHUB_PREFIX}/scripts")

    # ------------------------------------------------------------------
    # State
    # ------------------------------------------------------------------

    def _assemble_state(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for file_path in registry.state_files():
            content = file_path.read_text()
            rel = f"{self.GITHUB_PREFIX}/state/{file_path.name}"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Artifacts
    # ------------------------------------------------------------------

    def _assemble_artifacts(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for file_path in registry.artifacts_files():
            content = file_path.read_text()
            rel = f"{self.GITHUB_PREFIX}/artifacts/{file_path.name}"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # .env.example
    # ------------------------------------------------------------------

    def _copy_env_example(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        env = registry.env_example_path()
        if env is not None:
            writer.copy(env, ".env.example")
