"""OpenCodeAssembler — generates OpenCode agent setup from canonical definitions."""

from __future__ import annotations

import json
from pathlib import Path

from assembler.base import PlatformAssembler
from assembler.registry import CanonicalRegistry
from assembler.templates import generate_agents_section, substitute_vars
from assembler.writer import FileWriter

# Capability → OpenCode permission-capability mapping.
OPENCODE_PERMISSION_MAP: dict[str, str] = {
    "read": "read",
    "edit": "edit",
    "search": "grep",
    "execute": "bash",
    "delegate": "task",
    "plan": "todowrite",
    "fetch": "webfetch",
}

OPENCODE_AGENTS_SECTION_LABELS: dict[str, str] = {
    "agents_dir": ".opencode/agent/",
    "agent_file_ext": ".md",
    "capability_field": "permission",
    "skills_dir_template": ".opencode/skill/<skill-name>/SKILL.md",
    "prompts_intro": "User-facing entry points are defined as command markdown files in `.opencode/command/`. Invoke them with a `/` slash command in the OpenCode CLI/TUI:",
    "prompt_file_ext": ".md",
    "instructions_intro": "Persistent rules are defined as plain markdown files under `.opencode/instructions/` and referenced by path in the `instructions` array of `opencode.json`:",
    "instruction_file_ext": ".md",
    "model_tiers_intro": "`opencode.json`'s `model`/`small_model` fields and each agent's frontmatter `model` field reference tiers resolved from `canonical/model-tiers.yaml`. Tier assignment reflects cost/capability trade-offs:",
}


class OpenCodeAssembler(PlatformAssembler):
    name = "opencode"

    TEMPLATE_VARS: dict[str, str] = {
        "PROJECT_INSTRUCTIONS_FILE": "AGENTS.md",
        "AGENTS_DIR": ".opencode",
        "TASK_TRACKING_INSTRUCTION": "use the `todowrite` tool to plan the tasks",
        "TASK_COMPLETION_INSTRUCTION": "Mark each task as completed via `todowrite` immediately after finishing it",
    }

    OPENCODE_PREFIX = ".opencode"

    def assemble(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        self._assemble_agents(registry, writer)
        self._assemble_skills(registry, writer)
        self._assemble_instructions(registry, writer)
        self._assemble_prompts(registry, writer)
        self._assemble_project_instructions(registry, writer)
        self._assemble_config(registry, writer)
        self._assemble_state(registry, writer)
        self._assemble_artifacts(registry, writer)
        self._assemble_readme(registry, writer)
        self._copy_platform_extras(registry, writer)
        self._copy_env_example(registry, writer)

    # ------------------------------------------------------------------
    # Agents
    # ------------------------------------------------------------------

    def _assemble_agents(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        all_subagent_slugs = {s for a in registry.agents for s in a.get("subagents", [])}
        for agent in registry.agents:
            slug = agent["slug"]
            tier = agent["tier"]
            model = registry.model_for_tier(tier, self.name)
            body = substitute_vars(registry.agent_body(slug), self.TEMPLATE_VARS)

            if slug in all_subagent_slugs and agent.get("user_invocable"):
                mode = "all"
            elif agent.get("user_invocable"):
                mode = "primary"
            else:
                mode = "subagent"

            perms = sorted({OPENCODE_PERMISSION_MAP.get(c, c) for c in agent.get("capabilities", [])})

            lines: list[str] = ["---"]
            lines.append(f'description: "{agent["description"]}"')
            lines.append(f"mode: {mode}")
            lines.append(f'model: "{model}"')
            lines.append("permission:")
            for perm in perms:
                lines.append(f"  {perm}: allow")
            lines.append("---")
            lines.append("")
            lines.append(f"<!-- tier: {tier} -->")
            lines.append("")
            lines.append(f"<!-- DO NOT EDIT — generated by scripts/assemble.py from canonical/agents/{slug}.md -->")
            lines.append("")

            content = "\n".join(lines) + body
            rel = f"{self.OPENCODE_PREFIX}/agent/{slug}.md"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Skills
    # ------------------------------------------------------------------

    def _assemble_skills(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for skill in registry.skills:
            slug = skill["slug"]
            body = registry.skill_body(slug)

            lines: list[str] = ["---"]
            lines.append(f"name: {slug}")
            lines.append(f"description: '{skill['description']}'")
            lines.append("---")
            lines.append("")

            content = "\n".join(lines) + body
            rel = f"{self.OPENCODE_PREFIX}/skill/{slug}/SKILL.md"
            writer.put(rel, content)

            scripts_dir = registry.skill_scripts_dir(slug)
            if scripts_dir is not None:
                writer.copy_tree(
                    scripts_dir,
                    f"{self.OPENCODE_PREFIX}/skill/{slug}/scripts",
                )

    # ------------------------------------------------------------------
    # Instructions
    # ------------------------------------------------------------------

    def _assemble_instructions(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for instr in registry.instructions:
            slug = instr["slug"]
            body = registry.instruction_body(slug)
            rel = f"{self.OPENCODE_PREFIX}/instructions/{slug}.md"
            writer.put(rel, body)

    # ------------------------------------------------------------------
    # Prompts
    # ------------------------------------------------------------------

    def _assemble_prompts(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for prompt in registry.prompts:
            slug = prompt["slug"]
            body = registry.prompt_body(slug)

            lines: list[str] = ["---"]
            lines.append(f'description: "{prompt["description"]}"')
            lines.append(f'agent: {prompt["agent"]}')
            lines.append("---")
            lines.append("")
            lines.append(f'> **Argument hint**: {prompt["argument_hint"]}')
            lines.append("")
            lines.append("$ARGUMENTS")
            lines.append("")

            content = "\n".join(lines) + body
            rel = f"{self.OPENCODE_PREFIX}/command/{slug}.md"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Project instructions (AGENTS.md)
    # ------------------------------------------------------------------

    def _assemble_project_instructions(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        tpl = registry.project_instructions_tpl
        start_marker = "<!-- AGENTS_SECTION:AUTO_GENERATED -->"
        tables_marker = "<!-- AGENTS_SECTION:DYNAMIC_TABLES -->"

        if tables_marker in tpl:
            dynamic_tables = generate_agents_section(
                registry, self.name, "AGENTS.md", labels=OPENCODE_AGENTS_SECTION_LABELS
            )
            content = tpl.replace(tables_marker, dynamic_tables)
        elif start_marker in tpl:
            agents_section = generate_agents_section(
                registry, self.name, "AGENTS.md", labels=OPENCODE_AGENTS_SECTION_LABELS
            )
            content = tpl.replace(start_marker, start_marker + "\n" + agents_section)
        else:
            content = tpl

        content = self.substitute(content)
        writer.put("AGENTS.md", content)

    # ------------------------------------------------------------------
    # OpenCode config (opencode.json)
    # ------------------------------------------------------------------

    def _assemble_config(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        config = {
            "$schema": "https://opencode.ai/config.json",
            "model": registry.model_for_tier(2, self.name),
            "small_model": registry.model_for_tier(0, self.name),
            "instructions": [f"{self.OPENCODE_PREFIX}/instructions/*.md"],
        }
        if any(a["slug"] == "orchestrator" for a in registry.agents):
            config["default_agent"] = "orchestrator"
        content = json.dumps(config, indent=2, ensure_ascii=False) + "\n"
        writer.put("opencode.json", content)

    # ------------------------------------------------------------------
    # README
    # ------------------------------------------------------------------

    def _assemble_readme(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        extras = registry.platform_extras_dir(self.name)
        if extras is None:
            return
        tpl_path = extras / "README.md.tpl"
        if not tpl_path.exists():
            return
        content = self.substitute(tpl_path.read_text())
        writer.put(f"{self.OPENCODE_PREFIX}/README.md", content)

    def _copy_platform_extras(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        extras = registry.platform_extras_dir(self.name)
        if extras is not None:
            for src_file in sorted(extras.rglob("*")):
                if src_file.is_file() and src_file.suffix != ".tpl":
                    file_rel = Path(f"{self.OPENCODE_PREFIX}/scripts") / src_file.relative_to(extras)
                    writer.copy(src_file, file_rel)

    # ------------------------------------------------------------------
    # State
    # ------------------------------------------------------------------

    def _assemble_state(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        if writer.check_protected_dir(f"{self.OPENCODE_PREFIX}/state/archive"):
            writer.add_warning(
                f"{self.OPENCODE_PREFIX}/state/archive/ is not empty. "
                "Skipping state assembly to protect archived workflow state files."
            )
            return

        for file_path in registry.state_files():
            content = file_path.read_text()
            rel = f"{self.OPENCODE_PREFIX}/state/{file_path.name}"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # Artifacts
    # ------------------------------------------------------------------

    def _assemble_artifacts(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        artifacts_dir = Path(self.OPENCODE_PREFIX) / "artifacts"
        if writer.check_protected_dir(str(artifacts_dir)):
            writer.add_warning(
                f"{artifacts_dir}/REGISTRY.md is agent-managed. "
                "Skipping artifacts assembly to protect accumulated workflow registry."
            )
            return

        for file_path in registry.artifacts_files():
            content = file_path.read_text()
            rel = f"{self.OPENCODE_PREFIX}/artifacts/{file_path.name}"
            writer.put(rel, content)

    # ------------------------------------------------------------------
    # .env.example
    # ------------------------------------------------------------------

    def _copy_env_example(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        env = registry.env_example_path()
        if env is not None:
            writer.copy(env, ".env.example")
