"""AiderAssembler — generates the Aider-facing package from canonical definitions.

Unlike Copilot, Aider has no native multi-agent orchestration or custom-agent
concept. This adapter emits *data only*: agent bodies (used as system prompts
by the installed `jira2pr` runtime engine), a resolved model config, and a
couple of Aider CLI config files. Execution is driven by the `jira2pr`
package itself (see `runtime/workflow/executor.py`) — no Python is generated
into the target repo, so there is nothing here to drift out of sync with the
engine that runs it.
"""

from __future__ import annotations

import yaml

from assembler.base import PlatformAssembler
from assembler.core_package import assemble_core
from assembler.registry import CanonicalRegistry
from assembler.templates import execution_policy_vars
from assembler.writer import FileWriter

CORE_PREFIX = ".jira2pr"


class AiderAssembler(PlatformAssembler):
    name = "aider"

    TEMPLATE_VARS: dict[str, str] = {
        "CORE_DIR": CORE_PREFIX,
    }

    def assemble(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        self.TEMPLATE_VARS = {**self.TEMPLATE_VARS, **execution_policy_vars(registry.execution_policy)}
        assemble_core(registry, writer, self.name, self.runtime_root)
        self._assemble_agent_bodies(registry, writer)
        self._assemble_aider_config(registry, writer)
        self._assemble_aider_cli_files(registry, writer)
        self._assemble_readme(registry, writer)

    # ------------------------------------------------------------------
    # Agent bodies (used as system prompts by runtime/workflow/worker_invoker.py)
    # ------------------------------------------------------------------

    def _assemble_agent_bodies(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for agent in registry.agents:
            body = self.substitute(registry.agent_body(agent.slug))
            header = (
                f"<!-- tier: {agent.model_tier} -->\n"
                f"<!-- DO NOT EDIT — generated by jira2pr from canonical/agents/{agent.slug}.md -->\n\n"
            )
            writer.put(f"{CORE_PREFIX}/agents/{agent.slug}.md", header + body)

    # ------------------------------------------------------------------
    # Backend config
    # ------------------------------------------------------------------

    def _assemble_aider_config(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        tiers = registry.model_tiers.get("tiers", {})
        tier_models = {
            str(tier_num): tier_data.get("models", {}).get(self.name, "")
            for tier_num, tier_data in tiers.items()
        }
        config = {
            "backend": "aider",
            "models": tier_models,
            "cli": {
                "base_args": ["--yes-always", "--no-auto-commits"],
            },
        }
        content = (
            "# Aider backend configuration.\n"
            "# `models` maps model-tier -> aider/LiteLLM model id (edit freely to\n"
            "# match whichever provider/API key you have configured).\n"
            + yaml.safe_dump(config, sort_keys=False)
        )
        writer.put(f"{CORE_PREFIX}/config/aider.yaml", content)

    def _assemble_aider_cli_files(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        default_model = registry.model_for_tier(2, self.name)
        writer.put(
            ".aider.conf.yml",
            (
                "# Generated by jira2pr. `jira2pr run` overrides --model per invocation\n"
                f"# from {CORE_PREFIX}/config/aider.yaml; this default only applies when\n"
                "# aider is run manually outside of jira2pr.\n"
                f"model: {default_model}\n"
                "auto-commits: false\n"
                "yes-always: false\n"
            ),
        )
        writer.put(
            ".aiderignore",
            f"{CORE_PREFIX}/state/\n{CORE_PREFIX}/.manifest.json\n",
        )

    # ------------------------------------------------------------------
    # README
    # ------------------------------------------------------------------

    def _assemble_readme(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        extras = registry.platform_extras_dir(self.name)
        if extras is None:
            return
        tpl_path = extras / "README.md.tpl"
        if not tpl_path.exists():
            return
        content = self.substitute(tpl_path.read_text())
        writer.put(f"{CORE_PREFIX}/README.md", content)
