"""AiderAssembler — generates the Aider-facing package from canonical definitions.

Unlike Copilot, Aider has no native multi-agent orchestration or custom-agent
concept. This adapter emits *data only*: agent bodies (used as system prompts
by the installed `jira2pr` runtime engine), a resolved model config, and a
couple of Aider CLI config files. Execution is driven by the `jira2pr`
package itself (see `runtime/workflow/executor.py`) — no Python is generated
into the target repo, so there is nothing here to drift out of sync with the
engine that runs it.
"""

from __future__ import annotations

import yaml

from assembler.base import PlatformAssembler
from assembler.core_package import assemble_core
from assembler.registry import CanonicalRegistry
from assembler.templates import execution_policy_vars, generate_agents_section
from assembler.writer import FileWriter

CORE_PREFIX = ".jira2pr"

AIDER_AGENTS_SECTION_LABELS: dict[str, str] = {
    "agents_dir": ".jira2pr/agents/",
    "agent_file_ext": ".md",
    "capability_field": "capability",
    "agent_definitions_note": (
        "Agent definitions live in `.jira2pr/agents/`. Each file is a plain Markdown "
        "system prompt with no frontmatter — capability wiring and model selection are "
        "determined at runtime by `canonical/workflows/shared/workers.yaml` and "
        "`.jira2pr/config/aider.yaml`, not by the agent file itself."
    ),
}


class AiderAssembler(PlatformAssembler):
    name = "aider"

    TEMPLATE_VARS: dict[str, str] = {
        "CORE_DIR": CORE_PREFIX,
    }

    def assemble(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        self.TEMPLATE_VARS = {**self.TEMPLATE_VARS, **execution_policy_vars(registry.execution_policy)}
        assemble_core(registry, writer, self.name, self.runtime_root)
        self._assemble_agent_bodies(registry, writer)
        self._assemble_project_instructions(registry, writer)
        self._assemble_aider_config(registry, writer)
        self._assemble_aider_cli_files(registry, writer)
        self._assemble_readme(registry, writer)
        self._assemble_runtime_prompts(writer)

    # ------------------------------------------------------------------
    # Agent bodies (used as system prompts by runtime/workflow/worker_invoker.py)
    # ------------------------------------------------------------------
    def _assemble_agent_bodies(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        for agent in registry.agents:
            # Aider has no orchestrator agent. Workflow orchestration is
            # performed by the jira2pr runtime.
            if agent.kind == "orchestrator":
                continue

            body = self.substitute(
                registry.agent_body(agent.slug)
            )

            header = (
                "<!-- DO NOT EDIT — generated by jira2pr from "
                f"canonical/agents/{agent.slug}.md -->\n\n"
            )

            writer.put(
                f"{CORE_PREFIX}/agents/{agent.slug}.md",
                header + body,
            )

    # ------------------------------------------------------------------
    # Project instructions (AGENTS.md)
    # ------------------------------------------------------------------

    def _assemble_project_instructions(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        tpl = registry.project_instructions_tpl
        models = registry.platform_models(self.name)
        start_marker = "<!-- AGENTS_SECTION:AUTO_GENERATED -->"
        tables_marker = "<!-- AGENTS_SECTION:DYNAMIC_TABLES -->"

        if tables_marker in tpl:
            dynamic_tables = generate_agents_section(
                registry, 
                self.name, 
                models=models,
                labels=AIDER_AGENTS_SECTION_LABELS, 
                include_orchestrator=False
            )
            content = tpl.replace(tables_marker, dynamic_tables)
        elif start_marker in tpl:
            agents_section = generate_agents_section(
                registry, 
                self.name, 
                models=models,
                labels=AIDER_AGENTS_SECTION_LABELS, 
                include_orchestrator=False
            )
            content = tpl.replace(start_marker, start_marker + "\n" + agents_section)
        else:
            content = tpl

        content = self.substitute(content)
        writer.put("AGENTS.md", content)

# ------------------------------------------------------------------
# Backend config
# ------------------------------------------------------------------

    def _assemble_aider_config(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        """Generate the runtime configuration for the Aider backend."""

        models = registry.platform_models(self.name)

        # Aider does not execute the orchestrator agent. Workflow orchestration
        # is performed by the jira2pr runtime.
        runtime_agents = {
            agent.slug
            for agent in registry.agents
            if agent.kind != "orchestrator"
        }

        missing_models = sorted(
            runtime_agents - set(models)
        )

        if missing_models:
            raise ValueError(
                "Aider model configuration is missing agent(s): "
                + ", ".join(missing_models)
            )

        # Keep only agents actually executed by the Aider runtime.
        resolved_models = {
            slug: models[slug]
            for slug in sorted(runtime_agents)
        }

        config = {
            "backend": "aider",
            "models": resolved_models,
            "cli": {
                "base_args": [
                    "--yes-always",
                    "--no-auto-commits",
                ],
            },
            "execution": {
                "artifact": {
                    "map_tokens": 0,
                },
                "structured": {
                    "map_tokens": 0,
                },
                "repository": {
                    "map_tokens": 4096,
                },
            },
        }

        content = (
            "# Aider backend configuration.\n"
            "#\n"
            "# `models` maps jira2pr agent slugs directly to Aider/LiteLLM\n"
            "# model identifiers. Edit these values to match the models and\n"
            "# providers available in your environment.\n"
            "#\n"
            "# `execution` controls Aider context behavior for each execution\n"
            "# mode. Artifact and structured workers use explicit file context;\n"
            "# repository workers such as coder may use the repository map.\n\n"
            + yaml.safe_dump(
                config,
                sort_keys=False,
            )
        )

        writer.put(
            f"{CORE_PREFIX}/config/aider.yaml",
            content,
        )

    def _assemble_aider_cli_files(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        writer.put(
            ".aider.conf.yml",
            "read:\n"
            "  - AGENTS.md\n"
            "\n"
            "git: true\n"
            "auto-commits: false\n"
            "\n"
            "map-tokens: 4096\n"
            "map-refresh: auto\n"
            "\n"
            "auto-lint: true\n"
            "\n"
            "pretty: true\n"
            "stream: true\n",
        )

        writer.put(
            ".aiderignore",
            f"{CORE_PREFIX}/state/\n"
            f"{CORE_PREFIX}/.manifest.json\n",
        )
    # ------------------------------------------------------------------
    # README
    # ------------------------------------------------------------------

    def _assemble_readme(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        extras = registry.platform_extras_dir(self.name)
        if extras is None:
            return
        tpl_path = extras / "README.md.tpl"
        if not tpl_path.exists():
            return
        content = self.substitute(tpl_path.read_text())
        writer.put(f"{CORE_PREFIX}/README.md", content)


    def _assemble_runtime_prompts(
        self,
        writer: FileWriter,
    ) -> None:
        """Copy all Aider runtime prompts into the generated package."""

        src_dir = (
            self.runtime_root
            / "backends"
            / "prompts"
        )

        if not src_dir.is_dir():
            raise FileNotFoundError(
                f"Aider runtime prompts directory not found: {src_dir}"
            )

        writer.copy_tree(
            src_dir,
            f"{CORE_PREFIX}/runtime/backends/prompts",
        )
