"""CopilotAssembler — generates VS Code Copilot agent setup from canonical definitions."""

from __future__ import annotations

from pathlib import Path

from assembler.base import PlatformAssembler
from assembler.core_package import assemble_core
from assembler.model import AgentSpec, WorkflowSpec
from assembler.registry import CanonicalRegistry
from assembler.templates import generate_agents_section
from assembler.writer import FileWriter

# Native (non-script) capability -> VS Code Copilot tool mapping.
# Script-backed capabilities always resolve to the "execute" tool.
COPILOT_NATIVE_TOOL_MAP: dict[str, str] = {
    "web.search": "fetch",
    "diff.read": "search",
    "test.results": "search",
}

CAPABILITY_HANDLER_SCRIPT_MAP = {
    "jira": ".jira2pr/runtime/integrations/jira.py",
    "git": ".jira2pr/runtime/integrations/git.py",
    "github": ".jira2pr/runtime/integrations/github.py",
}

CAPABILITY_ARGS_MAP = {
    "jira.read": ["<ticket_key_or_url>"],

    "git.status": ["status"],
    "git.commit": ["commit", "<message>"],
    "git.push": ["push"],

    "pr.update": [
        "update",
        "--pr-number",
        "<pr_number>",
        "--body-file",
        "<body_file>",
    ],
}

class CopilotAssembler(PlatformAssembler):
    name = "copilot"

    TEMPLATE_VARS: dict[str, str] = {
        "AGENTS_DIR": ".github",
        "CORE_DIR": ".jira2pr",
    }

    # The Copilot-specific UX shell lives under .github/; the platform-neutral
    # payload (workflows, artifacts, capabilities, state) lives under
    # .jira2pr/ via assemble_core() and is shared with the Aider adapter.
    GITHUB_PREFIX = ".github"

    def assemble(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        assemble_core(registry, writer, self.name, self.runtime_root)
        self._assemble_agents(registry, writer)
        self._assemble_prompts(registry, writer)
        self._assemble_instructions(registry, writer)
        self._assemble_project_instructions(registry, writer)
        self._assemble_readme(registry, writer)
        self._copy_platform_extras(registry, writer)

    # ------------------------------------------------------------------
    # Agents
    # ------------------------------------------------------------------

    def _tools_for_agent(self, agent: AgentSpec, registry: CanonicalRegistry) -> list[str]:
        tools = {"read", "edit"}
        binding = registry.workers.get(agent.slug)
        if binding is not None:
            for cap_id in binding.runtime_context:
                cap = registry.capabilities.get(cap_id)
                if cap is None:
                    continue
                if cap.binding.kind == "script":
                    tools.add("execute")
                else:
                    tools.add(COPILOT_NATIVE_TOOL_MAP.get(cap_id, "search"))
            if binding.actions:
                tools.add("execute")
            if binding.can_delegate:
                tools.add("agent")
        if agent.kind == "supervisor":
            tools.add("agent")
            tools.add("plan")
        return sorted(tools)

    def _assemble_agents(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        worker_slugs = [a.slug for a in registry.agents if a.kind == "worker"]
        for agent in registry.agents:
            model = registry.model_for_tier(agent.model_tier, self.name)
            body = registry.agent_body(agent.slug)
            binding = registry.workers.get(agent.slug)

            lines: list[str] = ["---"]
            lines.append(f'description: "{agent.description}"')
            lines.append(f'name: "{agent.name}"')
            lines.append(f"tools: [{', '.join(self._tools_for_agent(agent, registry))}]")
            lines.append(f'model: "{model}"')
            if agent.kind == "supervisor":
                lines.append(f"agents: [{', '.join(worker_slugs)}]")
                lines.append('argument-hint: "JIRA ticket key/URL, or ticket key to resume"')
                lines.append("user-invocable: true")
            else:
                if binding and binding.can_delegate:
                    lines.append(f"agents: [{', '.join(binding.can_delegate)}]")
                lines.append("user-invocable: false")
            lines.append("---")
            lines.append("")
            lines.append(f"<!-- tier: {agent.model_tier} -->")
            lines.append("")
            lines.append(
                f"<!-- DO NOT EDIT — generated by jira2pr from canonical/agents/{agent.slug}.md -->"
            )
            lines.append("")
            content = "\n".join(lines) + body
            writer.put(f"{self.GITHUB_PREFIX}/agents/{agent.slug}.agent.md", content)

    # ------------------------------------------------------------------
    # Prompts (one per workflow, plus resume/status)
    # ------------------------------------------------------------------

    def _assemble_prompts(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        for workflow in sorted(registry.workflows.values(), key=lambda w: w.name):
            content = self._render_workflow_prompt(workflow, registry)
            writer.put(f"{self.GITHUB_PREFIX}/prompts/{workflow.name}.prompt.md", content)

        writer.put(f"{self.GITHUB_PREFIX}/prompts/resume.prompt.md", self._render_resume_prompt(registry))
        writer.put(f"{self.GITHUB_PREFIX}/prompts/status.prompt.md", self._render_status_prompt(registry))

    def _render_workflow_prompt(self, workflow: WorkflowSpec, registry: CanonicalRegistry) -> str:
        core_dir = self.TEMPLATE_VARS["CORE_DIR"]
        agents_dir = self.TEMPLATE_VARS["AGENTS_DIR"]
        lines = ["---"]
        lines.append(f'description: "Run the {workflow.name} workflow end-to-end from a JIRA ticket."')
        lines.append('agent: "supervisor"')
        lines.append('argument-hint: "JIRA ticket key (e.g., PROJ-123) or URL"')
        lines.append("---")
        lines.append("")
        lines.append(f"# /{workflow.name}")
        lines.append("")
        lines.append(
            f"Execute the `{workflow.name}` workflow defined in "
            f"`{core_dir}/workflows/{workflow.name}.workflow.yaml`, starting from `{workflow.initial_state}`."
        )
        lines.append("")
        lines.append("## States")
        lines.append("")
        lines.append("| State | Worker | Success Criteria | Max Attempts |")
        lines.append("|-------|--------|-------------------|---------------|")
        for state in workflow.states.values():
            if state.terminal:
                lines.append(f"| `{state.name}` | — | terminal (outcome: {state.outcome}) | — |")
                continue
            attempts = (
                state.max_attempts
                if state.max_attempts is not None
                else registry.execution_policy.default_max_attempts
            )
            lines.append(
                f"| `{state.name}` | `{state.worker}` | `{state.success_criteria}` | {attempts} |"
            )
        lines.append("")
        lines.append(
            "For each non-terminal state: invoke the named worker agent, then invoke "
            "`supervisor` to evaluate its output against the state's success criteria "
            f"(see `{agents_dir}/instructions/workflow-protocol.instructions.md` for the full "
            f"protocol and `{core_dir}/artifacts/` for artifact schemas). Persist the outcome to "
            f"`{core_dir}/state/<TICKET-KEY>.yaml` before transitioning to the next state."
        )
        return "\n".join(lines) + "\n"

    def _render_resume_prompt(self, registry: CanonicalRegistry) -> str:
        core_dir = self.TEMPLATE_VARS["CORE_DIR"]
        workflow_names = ", ".join(f"`{w}`" for w in sorted(registry.workflows))
        lines = [
            "---",
            'description: "Resume an in-progress workflow from its persisted state file."',
            'agent: "supervisor"',
            'argument-hint: "JIRA ticket key (e.g., PROJ-123)"',
            "---",
            "",
            "# /resume",
            "",
            f"Load `{core_dir}/state/<TICKET-KEY>.yaml`, determine `workflow` and `current_state`, "
            f"and continue executing from there. Supported workflows: {workflow_names}.",
        ]
        return "\n".join(lines) + "\n"

    def _render_status_prompt(self, registry: CanonicalRegistry) -> str:
        core_dir = self.TEMPLATE_VARS["CORE_DIR"]
        lines = [
            "---",
            'description: "Report the current status of a workflow without executing anything."',
            'agent: "supervisor"',
            'argument-hint: "JIRA ticket key (e.g., PROJ-123)"',
            "---",
            "",
            "# /status",
            "",
            f"Read `{core_dir}/state/<TICKET-KEY>.yaml` (read-only) and report `workflow`, "
            "`current_state`, `status`, `retry_counts`, and `history`. Do not invoke any "
            "worker or modify state.",
        ]
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Instructions
    # ------------------------------------------------------------------

    def _assemble_instructions(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        writer.put(
            f"{self.GITHUB_PREFIX}/instructions/workflow-protocol.instructions.md",
            self._render_workflow_protocol(registry),
        )
        writer.put(
            f"{self.GITHUB_PREFIX}/instructions/capabilities.instructions.md",
            self._render_capabilities_instructions(registry),
        )
        writer.put(
            f"{self.GITHUB_PREFIX}/instructions/artifact-schemas.instructions.md",
            self._render_artifact_schemas_instructions(registry),
        )

    def _render_workflow_protocol(self, registry: CanonicalRegistry) -> str:
        policy = registry.execution_policy
        lines = [
            "---",
            'description: "How to evaluate worker output and transition between workflow states."',
            "---",
            "",
            "# Workflow Protocol",
            "",
            f"Every state has bounded retries (default max attempts: {policy.default_max_attempts}). "
            f"Exhausting retries **{policy.on_exhaustion}s** the workflow rather than looping forever.",
            "",
            "## Success Criteria",
            "",
            "| Key | Required Labels |",
            "|-----|------------------|",
        ]
        for key, labels in sorted(registry.success_criteria.criteria.items()):
            lines.append(f"| `{key}` | {', '.join(labels)} |")
        lines.append("")
        lines.append(
            f"Evaluation mode: **{policy.criteria_mode}** — every label must be satisfied for "
            "the outcome to be `success`."
        )
        lines.append("")
        lines.append("## Supervisor Output Schema")
        lines.append("")
        lines.append("```json")
        lines.append(
            '{"outcome": "success|failure|escalate", "reason": "...", "feedback": "...", "violations": []}'
        )
        lines.append("```")
        lines.append("")
        lines.append("## Criteria Evaluation Rules")
        lines.append("")
        for rule in registry.supervisor_contract.criteria_evaluation:
            lines.append(f"- {rule}")
        lines.append("")
        lines.append(
            f"Terminal states: `{policy.terminal_success_state}` (outcome: success), "
            f"`{policy.terminal_escalated_state}` (outcome: escalated)."
        )
        return "\n".join(lines) + "\n"

    def _render_capabilities_instructions(self, registry: CanonicalRegistry) -> str:
        lines = [
            "---",
            'description: "How each capability resolves to a runtime binding."',
            "---",
            "",
            "# Capabilities",
            "",
            "| Capability | Type | Resolution |",
            "|------------|------|------------|",
        ]
        for cap in sorted(registry.capabilities.values(), key=lambda c: c.id):
            if cap.binding.kind == "native":
                resolution = "native platform tool"
            else:
                script = CAPABILITY_HANDLER_SCRIPT_MAP[cap.binding.handler]
                args = CAPABILITY_ARGS_MAP.get(cap.id, [])
                resolution = f"`python3 {script} {' '.join(args)}`"
            lines.append(f"| `{cap.id}` | {cap.type} | {resolution} |")
        return "\n".join(lines) + "\n"

    def _render_artifact_schemas_instructions(self, registry: CanonicalRegistry) -> str:
        core_dir = self.TEMPLATE_VARS["CORE_DIR"]
        lines = [
            "---",
            'description: "Index of artifact schemas each worker must conform to."',
            "---",
            "",
            "# Artifact Schemas",
            "",
            f"Full schema text lives in `{core_dir}/artifacts/`:",
            "",
        ]
        for agent in registry.agents:
            if agent.artifact_schema:
                lines.append(
                    f"- **{agent.name}** produces artifacts conforming to "
                    f"`{core_dir}/artifacts/{agent.artifact_schema}`"
                )
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Project instructions (copilot-instructions.md)
    # ------------------------------------------------------------------

    def _assemble_project_instructions(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        tpl = registry.project_instructions_tpl
        tables_marker = "<!-- AGENTS_SECTION:DYNAMIC_TABLES -->"

        if tables_marker in tpl:
            dynamic_tables = generate_agents_section(registry, self.name)
            content = tpl.replace(tables_marker, dynamic_tables)
        else:
            content = tpl

        content = self.substitute(content)
        writer.put(f"{self.GITHUB_PREFIX}/copilot-instructions.md", content)

    # ------------------------------------------------------------------
    # README + platform extras
    # ------------------------------------------------------------------

    def _assemble_readme(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        extras = registry.platform_extras_dir(self.name)
        if extras is None:
            return
        tpl_path = extras / "README.md.tpl"
        if not tpl_path.exists():
            return
        content = self.substitute(tpl_path.read_text())
        writer.put(f"{self.GITHUB_PREFIX}/README.md", content)

    def _copy_platform_extras(self, registry: CanonicalRegistry, writer: FileWriter) -> None:
        extras = registry.platform_extras_dir(self.name)
        if extras is None:
            return
        for src_file in sorted(extras.rglob("*")):
            if src_file.is_file() and src_file.suffix != ".tpl":
                file_rel = Path(f"{self.GITHUB_PREFIX}/scripts") / src_file.relative_to(extras)
                writer.copy(src_file, file_rel)

