"""RuntimeAssembler - generates the Jira2PR runtime-driven package.

The runtime platform uses the installed Jira2PR Python runtime for workflow
orchestration.

Unlike agent-driven platforms such as GitHub Copilot, the runtime platform
does not require an orchestrator agent. Workflow transitions, persistence,
retry handling, capability execution, and backend routing are performed by
the Jira2PR runtime.

LLM execution uses the composite Jira2PR backend:

    artifact generation   -> LiteLLM
    structured generation -> LiteLLM
    repository editing    -> Aider

This assembler emits data and configuration only. No workflow-engine Python
is generated into the target repository, so runtime behavior remains owned by
the installed Jira2PR package.
"""

from __future__ import annotations

import typing

import yaml

from assembler.base import PlatformAssembler
from assembler.core_package import assemble_core
from assembler.registry import CanonicalRegistry
from assembler.templates import execution_policy_vars, generate_agents_section
from assembler.writer import FileWriter


CORE_PREFIX = ".jira2pr"


RUNTIME_AGENTS_SECTION_LABELS: dict[str, str] = {
    "agents_dir": ".jira2pr/agents/",
    "agent_file_ext": ".md",
    "capability_field": "capability",
    "agent_definitions_note": (
        "Agent definitions live in `.jira2pr/agents/`. Each file is a plain "
        "Markdown system prompt with no frontmatter. Capability wiring is "
        "determined by `canonical/workflows/shared/workers.yaml`, while model "
        "selection and execution settings are provided by "
        "`.jira2pr/config/runtime.yaml`."
    ),
}


class RuntimeAssembler(PlatformAssembler):
    """Assemble the Jira2PR runtime-driven platform package."""

    name = "runtime"

    TEMPLATE_VARS: typing.ClassVar[dict[str, str]] = {
        "CORE_DIR": CORE_PREFIX,
    }

    def assemble(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        """Generate the runtime-driven Jira2PR package."""

        self.TEMPLATE_VARS = {
            **self.TEMPLATE_VARS,
            **execution_policy_vars(
                registry.execution_policy
            ),
        }

        assemble_core(
            registry,
            writer,
            self.name,
            self.runtime_root,
        )

        self._assemble_agent_bodies(
            registry,
            writer,
        )

        self._assemble_project_instructions(
            registry,
            writer,
        )

        self._assemble_runtime_config(
            registry,
            writer,
        )

        self._assemble_aider_cli_files(
            registry,
            writer,
        )

        self._assemble_readme(
            registry,
            writer,
        )

        self._assemble_runtime_prompts(
            writer,
        )

    # ------------------------------------------------------------------
    # Agent bodies
    # ------------------------------------------------------------------

    def _assemble_agent_bodies(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        """Generate runtime agent prompts.

        The runtime platform does not generate the orchestrator agent because
        workflow orchestration is performed by the Jira2PR Python runtime.
        """

        for agent in registry.agents:
            if agent.kind == "orchestrator":
                continue

            body = self.substitute(
                registry.agent_body(
                    agent.slug
                )
            )

            header = (
                "<!-- DO NOT EDIT - generated by jira2pr from "
                f"canonical/agents/{agent.slug}.md -->\n\n"
            )

            writer.put(
                f"{CORE_PREFIX}/agents/{agent.slug}.md",
                header + body,
            )

    # ------------------------------------------------------------------
    # Project instructions
    # ------------------------------------------------------------------

    def _assemble_project_instructions(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        """Generate the repository-level AGENTS.md file."""

        tpl = registry.project_instructions_tpl

        models = registry.platform_models(
            self.name
        )

        start_marker = (
            "<!-- AGENTS_SECTION:AUTO_GENERATED -->"
        )

        tables_marker = (
            "<!-- AGENTS_SECTION:DYNAMIC_TABLES -->"
        )

        if tables_marker in tpl:
            dynamic_tables = generate_agents_section(
                registry,
                self.name,
                models=models,
                labels=RUNTIME_AGENTS_SECTION_LABELS,
                include_orchestrator=False,
            )

            content = tpl.replace(
                tables_marker,
                dynamic_tables,
            )

        elif start_marker in tpl:
            agents_section = generate_agents_section(
                registry,
                self.name,
                models=models,
                labels=RUNTIME_AGENTS_SECTION_LABELS,
                include_orchestrator=False,
            )

            content = tpl.replace(
                start_marker,
                start_marker
                + "\n"
                + agents_section,
            )

        else:
            content = tpl

        content = self.substitute(
            content
        )

        writer.put(
            "AGENTS.md",
            content,
        )

    # ------------------------------------------------------------------
    # Runtime configuration
    # ------------------------------------------------------------------

    def _assemble_runtime_config(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        """Generate configuration for the Jira2PR runtime platform."""

        models = registry.platform_models(
            self.name
        )

        # The runtime platform does not execute the orchestrator agent.
        # Workflow orchestration is performed by WorkflowExecutor.
        runtime_agents = {
            agent.slug
            for agent in registry.agents
            if agent.kind != "orchestrator"
        }

        missing_models = sorted(
            runtime_agents
            - set(models)
        )

        if missing_models:
            raise ValueError(
                "Runtime model configuration is missing agent(s): "
                + ", ".join(
                    missing_models
                )
            )

        resolved_models = {
            slug: models[slug]
            for slug in sorted(
                runtime_agents
            )
        }

        config = {
            "backend": "jira2pr",
            "models": resolved_models,
            "backends": {
                "generation": "litellm",
                "repository": "aider",
            },
            "cli": {
                "base_args": [
                    "--yes-always",
                    "--no-auto-commits",
                ],
            },
            "execution": {
                "artifact": {
                    "map_tokens": 0,
                },
                "planning": {
                    "map_tokens": 4096,
                },
                "structured": {
                    "map_tokens": 0,
                },
                "repository": {
                    "map_tokens": 5120,
                },
            },
            "verification": {
                "test_command": "make test",
                "lint_command": "make lint",
            },
        }

        content = (
            "# Jira2PR runtime platform configuration.\n"
            "#\n"
            "# `models` maps Jira2PR agent slugs directly to model identifiers.\n"
            "# Content-producing workers are executed through LiteLLM, while\n"
            "# repository-editing workers are executed through Aider.\n"
            "#\n"
            "# `execution` controls execution-mode-specific settings. Repository\n"
            "# map settings apply when Aider is used for repository-aware work.\n"
            "#\n"
            "# `verification` defines deterministic commands used to evaluate\n"
            "# implementation output.\n\n"
            + yaml.safe_dump(
                config,
                sort_keys=False,
            )
        )

        writer.put(
            f"{CORE_PREFIX}/config/runtime.yaml",
            content,
        )

    # ------------------------------------------------------------------
    # Aider repository-editor configuration
    # ------------------------------------------------------------------

    def _assemble_aider_cli_files(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        """Generate Aider configuration used by repository-editing workers.

        Aider is an implementation detail of the runtime platform rather than
        the platform itself. These files configure Aider when Jira2PR invokes
        it for repository editing.
        """

        writer.put(
            ".aider.conf.yml",
            "read:\n"
            "  - AGENTS.md\n"
            "\n"
            "git: true\n"
            "auto-commits: false\n"
            "\n"
            "map-tokens: 4096\n"
            "map-refresh: auto\n"
            "\n"
            "auto-lint: true\n"
            "\n"
            "pretty: true\n"
            "stream: true\n",
        )

        writer.put(
            ".aiderignore",
            f"{CORE_PREFIX}/state/\n"
            f"{CORE_PREFIX}/.manifest.json\n",
        )

    # ------------------------------------------------------------------
    # README
    # ------------------------------------------------------------------

    def _assemble_readme(
        self,
        registry: CanonicalRegistry,
        writer: FileWriter,
    ) -> None:
        """Generate the runtime platform README when a template exists."""

        extras = registry.platform_extras_dir(
            self.name
        )

        if extras is None:
            return

        tpl_path = (
            extras
            / "README.md.tpl"
        )

        if not tpl_path.exists():
            return

        content = self.substitute(
            tpl_path.read_text(
                encoding="utf-8"
            )
        )

        writer.put(
            f"{CORE_PREFIX}/README.md",
            content,
        )

    # ------------------------------------------------------------------
    # Runtime backend prompts
    # ------------------------------------------------------------------

    def _assemble_runtime_prompts(
        self,
        writer: FileWriter,
    ) -> None:
        """Copy runtime backend prompts into the generated package.

        The prompt directory contains execution prompts for both LiteLLM
        content generation and Aider repository editing.
        """

        src_dir = (
            self.runtime_root
            / "backends"
            / "prompts"
        )

        if not src_dir.is_dir():
            raise FileNotFoundError(
                "Runtime backend prompts directory not found: "
                f"{src_dir}"
            )

        writer.copy_tree(
            src_dir,
            f"{CORE_PREFIX}/runtime/backends/prompts",
        )