#!/usr/bin/env python3
"""Assemble platform-specific agent files from canonical definitions.

Reads:
    .agents/_registry.yaml    — agent metadata (tier, capabilities, subagents, …)
    .agents/<slug>.md         — canonical agent body (platform-agnostic)

Writes:
    .github/agents/<slug>.agent.md   — VS Code Copilot adapter (YAML frontmatter + body)
    .claude/commands/<slug>.md       — Claude Code slash-command adapter

Platform mappings (tool names, model strings, frontmatter schemas) are defined
in PLATFORM_CONFIGS below.  To add a new platform, add an entry there and a
corresponding _render_<platform>() function.

Usage:
    python scripts/assemble_agents.py                  # assemble all platforms
    python scripts/assemble_agents.py --platform copilot
    python scripts/assemble_agents.py --platform claude
    python scripts/assemble_agents.py --check          # dry-run, exit 1 if files would change
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
import textwrap
from pathlib import Path

# Third-party — stdlib-only fallback so the script works without pyyaml in
# minimal environments.  If pyyaml is missing we use a tiny subset parser that
# covers the _registry.yaml structure.
try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    yaml = None  # type: ignore[assignment]

# ---------------------------------------------------------------------------
# Paths (relative to repo root)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / ".agents"
REGISTRY_PATH = AGENTS_DIR / "_registry.yaml"
GITHUB_AGENTS_DIR = REPO_ROOT / ".github" / "agents"
CLAUDE_COMMANDS_DIR = REPO_ROOT / ".claude" / "commands"
MODEL_TIERS_PATH = REPO_ROOT / ".github" / "model-tiers.json"

# ---------------------------------------------------------------------------
# Capability → platform tool mapping
# ---------------------------------------------------------------------------
COPILOT_TOOL_MAP: dict[str, str] = {
    "read": "read",
    "edit": "edit",
    "search": "search",
    "execute": "execute",
    "delegate": "agent",
    "plan": "todo",
    "fetch": "fetch",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_yaml(path: Path) -> dict:
    """Load a YAML file.  Uses pyyaml when available, otherwise falls back to
    a minimal safe loader that handles the subset of YAML used in _registry.yaml."""
    text = path.read_text()
    if yaml is not None:
        return yaml.safe_load(text)
    # Minimal fallback: only supports the flat list-of-dicts structure of _registry.yaml.
    # This is intentionally limited — install pyyaml for full support.
    raise SystemExit(
        "pyyaml is not installed.  Install it (`pip install pyyaml`) or run "
        "this script inside the Docker container where it is available."
    )


def _load_model_tiers() -> dict[int, str]:
    """Return {tier_int: model_string} from .github/model-tiers.json."""
    data = json.loads(MODEL_TIERS_PATH.read_text())
    return {int(k): v["model"] for k, v in data["tiers"].items()}


def _read_canonical_body(slug: str) -> str:
    """Read the canonical agent markdown body from .agents/<slug>.md."""
    path = AGENTS_DIR / f"{slug}.md"
    if not path.exists():
        raise FileNotFoundError(f"Canonical agent file not found: {path}")
    return path.read_text()


# ---------------------------------------------------------------------------
# Copilot adapter renderer
# ---------------------------------------------------------------------------

def _render_copilot(agent: dict, body: str, model_tiers: dict[int, str]) -> str:
    """Render a VS Code Copilot .agent.md file (YAML frontmatter + body)."""
    tier = agent["tier"]
    model = model_tiers.get(tier, f"Tier-{tier} (unknown)")
    tools = [COPILOT_TOOL_MAP.get(c, c) for c in agent.get("capabilities", [])]
    subagents = agent.get("subagents", [])

    # Build YAML frontmatter lines
    lines: list[str] = ["---"]
    # description — quote it to handle colons
    lines.append(f'description: "{agent["description"]}"')
    lines.append(f'name: "{agent["name"]}"')
    if agent.get("role"):
        lines.append(f'role: "{agent["role"]}"')
    lines.append(f"tools: [{', '.join(tools)}]")
    lines.append(f'model: "{model}"')
    if subagents:
        lines.append(f"agents: [{', '.join(subagents)}]")
    lines.append(f'argument-hint: "{agent["argument_hint"]}"')
    lines.append(f"user-invocable: {'true' if agent.get('user_invocable') else 'false'}")
    lines.append("---")
    lines.append("")
    lines.append(f"<!-- tier: {tier} -->")
    lines.append("")
    lines.append(f"<!-- DO NOT EDIT — generated by scripts/assemble_agents.py from .agents/{agent['slug']}.md -->")
    lines.append("")

    return "\n".join(lines) + body


# ---------------------------------------------------------------------------
# Claude Code adapter renderer
# ---------------------------------------------------------------------------

def _render_claude_command(agent: dict, body: str) -> str:
    """Render a Claude Code slash-command file for .claude/commands/<slug>.md.

    Claude Code commands are plain Markdown.  We prepend a metadata comment
    block so both humans and tooling can parse the agent identity.
    """
    lines: list[str] = []
    lines.append(f"<!-- agent: {agent['slug']} -->")
    lines.append(f"<!-- name: {agent['name']} -->")
    lines.append(f"<!-- tier: {agent['tier']} -->")
    lines.append(f"<!-- generated by scripts/assemble_agents.py from .agents/{agent['slug']}.md -->")
    lines.append("")

    # Provide context preamble so Claude Code knows about the project setup
    preamble = textwrap.dedent(f"""\
        > **Agent**: {agent['name']}
        > **Argument**: {agent['argument_hint']}

        Read the project instructions from `CLAUDE.md` before proceeding.

    """)
    return "\n".join(lines) + preamble + body


# ---------------------------------------------------------------------------
# Main assembly logic
# ---------------------------------------------------------------------------

def assemble(platforms: list[str] | None = None, check: bool = False) -> bool:
    """Assemble agent adapter files for the requested platforms.

    Args:
        platforms: List of platform names to assemble.  ``None`` → all.
        check: If True, don't write files — just report whether they differ.

    Returns:
        True if all files are up-to-date (or were written successfully).
        False if ``check=True`` and files would change.
    """
    registry = _load_yaml(REGISTRY_PATH)
    agents: list[dict] = registry["agents"]
    model_tiers = _load_model_tiers()

    if platforms is None:
        platforms = ["copilot", "claude"]

    all_ok = True

    for agent in agents:
        slug = agent["slug"]
        body = _read_canonical_body(slug)

        for platform in platforms:
            if platform == "copilot":
                content = _render_copilot(agent, body, model_tiers)
                dest = GITHUB_AGENTS_DIR / f"{slug}.agent.md"
            elif platform == "claude":
                content = _render_claude_command(agent, body)
                dest = CLAUDE_COMMANDS_DIR / f"{slug}.md"
            else:
                print(f"WARNING: Unknown platform '{platform}', skipping.", file=sys.stderr)
                continue

            if check:
                if dest.exists():
                    existing = dest.read_text()
                    if existing != content:
                        diff = difflib.unified_diff(
                            existing.splitlines(keepends=True),
                            content.splitlines(keepends=True),
                            fromfile=str(dest.relative_to(REPO_ROOT)),
                            tofile=f"{dest.relative_to(REPO_ROOT)} (generated)",
                        )
                        sys.stdout.writelines(diff)
                        all_ok = False
                else:
                    print(f"MISSING: {dest.relative_to(REPO_ROOT)}", file=sys.stderr)
                    all_ok = False
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(content)
                print(f"  wrote {dest.relative_to(REPO_ROOT)}")

    return all_ok


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Assemble platform-specific agent files from canonical definitions."
    )
    parser.add_argument(
        "--platform",
        choices=["copilot", "claude"],
        action="append",
        help="Platform(s) to assemble.  Omit to assemble all.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Dry-run: exit 1 if any generated file would change.",
    )
    args = parser.parse_args()

    ok = assemble(platforms=args.platform, check=args.check)
    if args.check and not ok:
        print("\nAgent files are out of date.  Run `python scripts/assemble_agents.py` to regenerate.", file=sys.stderr)
        sys.exit(1)
    elif args.check:
        print("All agent files are up to date.")


if __name__ == "__main__":
    main()
